version: '3'

services:
 rabbitmq:
  image: rabbitmq
  ports:
   - 5672:5672
  networks:
   - jtechbe-network
 zipking:
  image: openzipkin/zipkin
  ports:
   - 9411:9411
  depends_on:
   - rabbitmq
  networks:
   - jtechbe-network
 eureka-naming-server:
  build: ./eurekaNamingServer
  volumes:
   - ./eurekaNamingServer:/volume
  ports:
   - 8761:8761
  networks:
   - jtechbe-network
 api-gateway-server:
  build: ./apiGatewayServer
  volumes:
   - ./apiGatewayServer:/volume
  ports:
   - 8755:8755
  networks:
   - jtechbe-network
  depends_on:
   - eureka-naming-server
   - zipking
  links:
   - eureka-naming-server
  environment:
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-naming-server:8761/eureka
  
 
networks:
 jtechbe-network:
  driver: overlay
