version: '3'

services:
 rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    expose:
      - "5672"
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - my-shared-network
 zipking:
  image: openzipkin/zipkin
  restart: on-failure
  ports:
   - "9411:9411"
  expose:
   - "9411"
  depends_on:
   - rabbitmq
  networks: 
    - my-shared-network
 eureka-naming-server:
  build: ./eurekaNamingServer
  restart: on-failure
  volumes:
   - ./eurekaNamingServer:/volume
  ports:
   - "8761:8761"
  expose:
   - "8761"
  networks: 
    - my-shared-network
 api-gateway-server:
  build: ./apiGatewayServer
  restart: on-failure
  volumes:
   - ./apiGatewayServer:/volume
  expose:
   - "8755"
  ports:
   - "8755:8755"
  networks: 
    - my-shared-network
  depends_on:
   - eureka-naming-server
   - zipking
   - rabbitmq
#  session-service:
#   build: ./sessionService
#   volumes:
#    - ./sessionService:/volume
#   expose:
#    - 8300
#   ports:
#    - 8300:8300
#   # network_mode: "host"
#   network_mode: "net1"
#   depends_on:
#    - eureka-naming-server
#    - zipking
#    - rabbitmq
#    - db
#   environment:
#     SPRING_RABBITMQ_HOST: rabbitmq
#  message-service:
#   build: ./messageService
#   volumes:
#    - ./messageService:/volume
#   expose:
#    - 8400
#   ports:
#    - 8400:8400
#   # network_mode: "host"
#   network_mode: "net1"
#   depends_on:
#    - eureka-naming-server
#    - zipking
#    - rabbitmq
#    - db
#   environment:
#     SPRING_RABBITMQ_HOST: rabbitmq   
#  notification-service:
#   build: ./notificationService
#   volumes:
#    - ./notificationService:/volume
#   expose:
#    - 8500
#   ports:
#    - 8500:8500
#   # network_mode: "host"
#   network_mode: "net1"
#   depends_on:
#    - eureka-naming-server
#    - zipking
#    - rabbitmq
#    - db
#   environment:
#     SPRING_RABBITMQ_HOST: rabbitmq
#  user-service:
#   build: ./userService
#   volumes:
#    - ./userService:/volume
#   expose:
#    - 8600
#   ports:
#    - 8600:8600
#   # network_mode: "host"
#   network_mode: "net1"
#   depends_on:
#    - eureka-naming-server
#    - zipking
#    - rabbitmq
#    - db
#   environment:
#     SPRING_RABBITMQ_HOST: rabbitmq
#  chatclient-service:
#   build: ./chatClientService
#   volumes:
#    - ./chatClientService:/volume
#   expose:
#    - 8200
#   ports:
#    - 8200:8200
#   # network_mode: "host"
#   network_mode: "net1"
#   depends_on:
#    - eureka-naming-server
#    - zipking
#    - rabbitmq
#   environment:
#     SPRING_RABBITMQ_HOST: rabbitmq
#  db:
#   image: mysql:8.0.18
#   restart: always
#   environment:
#    MYSQL_DATABASE: 'db'
#    MYSQL_USER: 'root'
#    MYSQL_PASSWORD: 'password'
#    MYSQL_ROOT_PASSWORD: 'password'
#   ports:
#    - '3306:3306'
#   expose:
#    - '3306'
#   volumes:
#    - jtechdb:/var/lib/mysql
#   # network_mode: "host"
#   network_mode: "net1"
volumes:
  jtechdb:
# networks:
#   net1:
#   new:
networks:
  my-shared-network: {}
