version: '3.5'

services:
    api-gateway-server:
        build:
            context: api-gateway
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - "8755"
        ports:
            - "8755:8755"
        networks:
            - jconnect-net
    session-service:
        build:
            context: session
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - 8300
        ports:
            - 8300:8300
        networks:
            - jconnect-net
        depends_on:
            - api-gateway-server
    message-service:
        build:
            context: messages
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - 8400
        ports:
            - 8400:8400
        networks:
            - jconnect-net
        depends_on:
            - api-gateway-server
    notification-service:
        build:
            context: notification
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - 8500
        ports:
            - 8500:8500
        networks:
            - jconnect-net
        depends_on:
            - api-gateway-server
    user-service:
        build:
            context: users
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - 8600
        ports:
            - 8600:8600
        depends_on:
            - api-gateway-server
        networks:
            - jconnect-net
    rest-api:
        build:
            context: rest-api
            dockerfile: Dockerfile
        volumes:
            - jconnect-services-vol:/tmp
        expose:
            - 8200
        ports:
            - 8200:8200
        networks:
            - jconnect-net
        depends_on:
            - api-gateway-server
volumes:
    jconnect-services-vol:
        name: jconnect-services-vol

networks:
    jconnect-net:
        external: true
