version: '3'

services:
 rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    network_mode: "host"
 zipking:
  image: openzipkin/zipkin
  ports:
   - 9411:9411
  depends_on:
   - rabbitmq
  network_mode: "host"
 eureka-naming-server:
  build: ./eurekaNamingServer
  volumes:
   - ./eurekaNamingServer:/volume
  ports:
   - 8761:8761
  network_mode: "host"
 api-gateway-server:
  build: ./apiGatewayServer
  volumes:
   - ./apiGatewayServer:/volume
  expose:
   - 8755
  ports:
   - 8755:8755
  network_mode: "host"
  depends_on:
   - eureka-naming-server
   - zipking
   - rabbitmq
 user-service:
  build: ./userService
  volumes:
   - ./userService:/volume
  expose:
   - 8600
  ports:
   - 8600:8600
  network_mode: "host"
  depends_on:
   - eureka-naming-server
   - zipking
   - rabbitmq
   - db
 session-service:
  build: ./sessionService
  volumes:
   - ./sessionServiceService:/volume
  expose:
   - 8300
  ports:
   - 8300:8300
  network_mode: "host"
  depends_on:
   - eureka-naming-server
   - zipking
   - rabbitmq
   - db

 db:
  image: mysql:8.0.18
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   MYSQL_USER: 'root'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - jtechdb:/var/lib/mysql
  network_mode: "host"
volumes:
  jtechdb:
