version: '3.5'
services:
    rabbitmq:
        container_name: jconnect-rabbitmq
        image: rabbitmq:management
        expose:
            - "5672"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - jconnect-net
    zipkin:
        container_name: jconnect-zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        expose:
            - "9411"
        networks:
            - jconnect-net
    elasticsearch:
        container_name: jconnect-elasticsearch
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            -   type: bind
                source: ./elasticsearch/config/elasticsearch.yml
                target: /usr/share/elasticsearch/config/elasticsearch.yml
                read_only: true
            -   type: volume
                source: jconnect-elasticsearch
                target: /usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
        networks:
            - jconnect-net
    logstash:
        container_name: jconnect-logstash
        build:
            context: logstash/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            -   type: bind
                source: ./logstash/config/logstash.yml
                target: /usr/share/logstash/config/logstash.yml
                read_only: true
            -   type: bind
                source: ./logstash/pipeline
                target: /usr/share/logstash/pipeline
                read_only: true
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - jconnect-net
        depends_on:
            - elasticsearch
    kibana:
        container_name: jconnect-kibana
        build:
            context: kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            -   type: bind
                source: ./kibana/config/kibana.yml
                target: /usr/share/kibana/config/kibana.yml
                read_only: true
        ports:
            - "5601:5601"
        networks:
            - jconnect-net
        depends_on:
            - elasticsearch
    config-server:
        container_name: jconnnect-config-server
        build:
            context: ../config-server
            dockerfile: Dockerfile
        expose:
            - 8888
        ports:
            - 8888:8888
        networks:
            - jconnect-net
    naming-server:
        container_name: jconnect-naming-server
        build:
            context: ../naming-server
            dockerfile: Dockerfile
        networks:
            - jconnect-net
        expose:
            - 8761
        ports:
            - 8761:8761
    db:
        container_name: jconnect-db
        image: mysql
        environment:
            MYSQL_DATABASE: 'spring_dev'
            MYSQL_USER: 'spring'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3336:3306'
        expose:
            - '3306'
        volumes:
            - jconnect-db-vol:/var/lib/mysql
        networks:
            - jconnect-net
volumes:
    jconnect-db-vol:
        name: jconnect-db-vol
    jconnect-elasticsearch:
        name: jconnect-elasticsearch
networks:
    jconnect-net:
        name: jconnect-net
